Adding _check_inputs() for error calculation functions (#279)
* feat: add _check_inputs() for all error metric calculation functions;

* fix: use corresponding lib to detect NaN, otherwise loss calculation during torch training will raise error...

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

* fix: don't check shapes for CRPS calc funcs;