fix: use corresponding lib to detect NaN, otherwise loss calculation during torch training will raise error...
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.