Use `setup` instead of `build` to build release (#114)
* fix: use setup instead of build;

* fix: remove bdist to generate only one dist;

To fix the error returned by PyPI website:
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
Only one sdist may be uploaded per release.